// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TouristAgency.DatabaseContext;

#nullable disable

namespace TouristAgency.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241031135854_ApiAuthMigration")]
    partial class ApiAuthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TouristAgency.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("FileExtention")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("ext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("fileName");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("mime");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("original");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TouristAgency.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("city");

                    b.Property<uint>("MFO")
                        .HasColumnType("int unsigned")
                        .HasColumnName("mfo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("TouristAgency.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("compaties");
                });

            modelBuilder.Entity("TouristAgency.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("TouristAgency.Entities.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TouristAgency.Entities.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TouristAgency.Entities.IndividualPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("lastName");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("middleName");

                    b.Property<string>("PassportDistributor")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("passportDistributor");

                    b.Property<DateTime>("PassportExpiredDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("passportExpiredDate");

                    b.Property<DateTime>("PassportMakeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("passportMakeDate");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("passportNumber");

                    b.Property<string>("PassportSerial")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("passportSerial");

                    b.HasKey("Id");

                    b.ToTable("IndividualPeople");
                });

            modelBuilder.Entity("TouristAgency.Entities.LegalPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BankId")
                        .HasColumnType("char(36)")
                        .HasColumnName("bankId");

                    b.Property<string>("BossFunction")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("bossFunction");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("bossName");

                    b.Property<string>("EDRPOU")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("edrpou");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("PaymentAccount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("paymentAccount");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("LegalPerson");
                });

            modelBuilder.Entity("TouristAgency.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("agentId");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("beginDate");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<Guid>("TourId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tourId");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("char(36)")
                        .HasColumnName("touristId");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TourId");

                    b.HasIndex("TouristId");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("TouristAgency.Entities.SocialNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SocialNetworks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fa0ce9c-8b07-4b41-85a7-82a60517a10a"),
                            Name = "Viber"
                        },
                        new
                        {
                            Id = new Guid("b6e69357-1782-461d-b0b9-9d6efd52a7f4"),
                            Name = "Telegram"
                        });
                });

            modelBuilder.Entity("TouristAgency.Entities.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tours");
                });

            modelBuilder.Entity("TouristAgency.Entities.TourCountry", b =>
                {
                    b.Property<Guid>("TourId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tourId");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("countryId");

                    b.HasKey("TourId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("tours_countries");
                });

            modelBuilder.Entity("TouristAgency.Entities.TourTourType", b =>
                {
                    b.Property<Guid>("TourId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tourId");

                    b.Property<Guid>("TourTypeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tourTypeId");

                    b.HasKey("TourId", "TourTypeId");

                    b.HasIndex("TourTypeId");

                    b.ToTable("tours_ tourTypes");
                });

            modelBuilder.Entity("TouristAgency.Entities.TourType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tourTypes");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsSMS")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sendSMS");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TouristProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("touristId");

                    b.HasKey("Id");

                    b.HasIndex("TouristProfileId");

                    b.ToTable("touristPhones");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristPhoneSocial", b =>
                {
                    b.Property<Guid>("PhoneId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SocialId")
                        .HasColumnType("char(36)");

                    b.HasKey("PhoneId", "SocialId");

                    b.HasIndex("SocialId");

                    b.ToTable("TPS");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birthday");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("city");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("comment");

                    b.Property<string>("EMail")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("lastName");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("middleName");

                    b.Property<bool>("NoSendNewslatter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("noSendNews");

                    b.Property<bool>("NoSendStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("noSendStatus");

                    b.HasKey("Id");

                    b.ToTable("touristProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c18ddec9-0af4-4017-9e30-96651267ac99"),
                            Address = "Живет где-то в Днепре",
                            Birthday = new DateTime(1978, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Днепр",
                            Comment = "Просто хороший человек",
                            FirstName = "Иван",
                            LastName = "Тестовый",
                            MiddleName = "Иванович",
                            NoSendNewslatter = false,
                            NoSendStatus = false
                        },
                        new
                        {
                            Id = new Guid("055b8af1-4aa9-45a9-a953-fe237731396a"),
                            Address = "Живет где-то в Киеве",
                            Birthday = new DateTime(1988, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Киев",
                            Comment = "Очень хороший человек",
                            FirstName = "Владимир",
                            LastName = "Тестовый",
                            MiddleName = "Иванович",
                            NoSendNewslatter = false,
                            NoSendStatus = false
                        },
                        new
                        {
                            Id = new Guid("c6880bd9-0d27-409f-87c9-7ccc940b19a6"),
                            Address = "Живет где-то в Сухачевке",
                            Birthday = new DateTime(1973, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Сухачевка",
                            Comment = "Просто хороший человек",
                            FirstName = "Тест",
                            LastName = "Иванов",
                            MiddleName = "Тестович",
                            NoSendNewslatter = false,
                            NoSendStatus = false
                        });
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristProfileTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tagId");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("char(36)")
                        .HasColumnName("touristId");

                    b.HasKey("TagId", "TouristId");

                    b.HasIndex("TouristId");

                    b.ToTable("tourists_tags");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("firstName");

                    b.HasKey("Id");

                    b.ToTable("tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa107d07-cfb3-4667-9a27-68d4bade0efe"),
                            TagName = "VIP"
                        },
                        new
                        {
                            Id = new Guid("7bc484f5-fbce-4542-a504-7d004076b4b0"),
                            TagName = "Горнолыжный отдых"
                        },
                        new
                        {
                            Id = new Guid("b07828a0-9ed4-4108-a3e1-aefeaa9e3a45"),
                            TagName = "Постоянный клиент"
                        },
                        new
                        {
                            Id = new Guid("a75d66c4-b4cc-45d1-bac4-39c992537b06"),
                            TagName = "Эконом"
                        },
                        new
                        {
                            Id = new Guid("f1315c23-42f2-4f87-9e59-f62a3a87d17d"),
                            TagName = "Активный отдых"
                        },
                        new
                        {
                            Id = new Guid("5fa72c14-5554-44b7-a5f0-f606b40d170c"),
                            TagName = "Ездит один"
                        },
                        new
                        {
                            Id = new Guid("11de133d-9f34-441c-8c1a-6bfc50cb51fa"),
                            TagName = "Семья"
                        },
                        new
                        {
                            Id = new Guid("5bbd4cf5-28d6-4627-8413-ec8dca5ad0e5"),
                            TagName = "Экскурсионный отдых"
                        });
                });

            modelBuilder.Entity("TouristAgency.Entities.Employee", b =>
                {
                    b.HasBaseType("TouristAgency.Entities.Identity.AppUser");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("companyId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("lastName");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("middleName");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("TouristAgency.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TouristAgency.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TouristAgency.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("TouristAgency.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TouristAgency.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TouristAgency.Entities.Company", b =>
                {
                    b.HasOne("TouristAgency.Entities.Bank", null)
                        .WithMany("Companies")
                        .HasForeignKey("BankId");
                });

            modelBuilder.Entity("TouristAgency.Entities.IndividualPerson", b =>
                {
                    b.HasOne("TouristAgency.Entities.TouristProfile", "Profile")
                        .WithOne("IndividualPersonData")
                        .HasForeignKey("TouristAgency.Entities.IndividualPerson", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TouristAgency.Entities.LegalPerson", b =>
                {
                    b.HasOne("TouristAgency.Entities.Bank", "Bank")
                        .WithMany("LegalPersons")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.TouristProfile", "Profile")
                        .WithOne("LegalPersonData")
                        .HasForeignKey("TouristAgency.Entities.LegalPerson", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TouristAgency.Entities.Sale", b =>
                {
                    b.HasOne("TouristAgency.Entities.Employee", "Agent")
                        .WithMany("Sales")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.Tour", "Tour")
                        .WithMany("Sales")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.TouristProfile", "Tourist")
                        .WithMany("Sales")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Tour");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TouristAgency.Entities.TourCountry", b =>
                {
                    b.HasOne("TouristAgency.Entities.Country", "Country")
                        .WithMany("CountryTour")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.Tour", "Tour")
                        .WithMany("CountryTour")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TouristAgency.Entities.TourTourType", b =>
                {
                    b.HasOne("TouristAgency.Entities.Tour", "Tour")
                        .WithMany("TourTourType")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.TourType", "TourType")
                        .WithMany("TourTourType")
                        .HasForeignKey("TourTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("TourType");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristPhone", b =>
                {
                    b.HasOne("TouristAgency.Entities.TouristProfile", "Tourist")
                        .WithMany("Phones")
                        .HasForeignKey("TouristProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristPhoneSocial", b =>
                {
                    b.HasOne("TouristAgency.Entities.TouristPhone", "TouristPhone")
                        .WithMany("TPS")
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.SocialNetwork", "SocialNetwork")
                        .WithMany("TPS")
                        .HasForeignKey("SocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialNetwork");

                    b.Navigation("TouristPhone");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristProfileTag", b =>
                {
                    b.HasOne("TouristAgency.Entities.TouristTag", "TouristTag")
                        .WithMany("ProfileTouristTag")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.TouristProfile", "TouristProfile")
                        .WithMany("ProfileTouristTag")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TouristProfile");

                    b.Navigation("TouristTag");
                });

            modelBuilder.Entity("TouristAgency.Entities.Employee", b =>
                {
                    b.HasOne("TouristAgency.Entities.Company", "Company")
                        .WithMany("Emploiees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TouristAgency.Entities.Identity.AppUser", null)
                        .WithOne()
                        .HasForeignKey("TouristAgency.Entities.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TouristAgency.Entities.Bank", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("LegalPersons");
                });

            modelBuilder.Entity("TouristAgency.Entities.Company", b =>
                {
                    b.Navigation("Emploiees");
                });

            modelBuilder.Entity("TouristAgency.Entities.Country", b =>
                {
                    b.Navigation("CountryTour");
                });

            modelBuilder.Entity("TouristAgency.Entities.SocialNetwork", b =>
                {
                    b.Navigation("TPS");
                });

            modelBuilder.Entity("TouristAgency.Entities.Tour", b =>
                {
                    b.Navigation("CountryTour");

                    b.Navigation("Sales");

                    b.Navigation("TourTourType");
                });

            modelBuilder.Entity("TouristAgency.Entities.TourType", b =>
                {
                    b.Navigation("TourTourType");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristPhone", b =>
                {
                    b.Navigation("TPS");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristProfile", b =>
                {
                    b.Navigation("IndividualPersonData");

                    b.Navigation("LegalPersonData");

                    b.Navigation("Phones");

                    b.Navigation("ProfileTouristTag");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("TouristAgency.Entities.TouristTag", b =>
                {
                    b.Navigation("ProfileTouristTag");
                });

            modelBuilder.Entity("TouristAgency.Entities.Employee", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
